title: DEVTIME
description: დეველოპერების დროა!
baseurl: ""
url: "https://devtime.ge"
fb:
  app_id: "879622035404501"
  default_image: "/img/devtime.png"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  auto_ids: false

paginate: 5
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
